# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt-get install npm -y
    init: sudo npm i -g browser-sync
    command: echo 'browser-sync start -s --https --no-open --port=5001'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5001
  - port: 3001
    onOpen: open-preview
