# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt-get python3
    init: echo 'python3 -m http.server 8001'
    #command: 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8001
  - port: 3001
    onOpen: open-preview
