# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
    echo 'init script' # runs during prebuild
    #echo 'sudo apt-get install npm'
    #echo 'sudo npm i -g browser-sync'
    #echo 'browser-sync start -s --https --no-open --port=5001'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5001
  - port: 3001
    onOpen: open-preview
